// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyZA1XyA9KZEgj-ubaQ5c0bsvLAR3OWsE',
    appId: '1:910614264123:web:dac85fc4d1d65053991f1e',
    messagingSenderId: '910614264123',
    projectId: 'ddwa-c76bf',
    authDomain: 'ddwa-c76bf.firebaseapp.com',
    storageBucket: 'ddwa-c76bf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxOixvh_NW1y1OC_03O9OWMg_Pf4eEKvA',
    appId: '1:910614264123:android:383f753899d85610991f1e',
    messagingSenderId: '910614264123',
    projectId: 'ddwa-c76bf',
    storageBucket: 'ddwa-c76bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAJmv7VMrnGOUKUegBDzP9z_yEU9HU-lk',
    appId: '1:910614264123:ios:d077eb5f888b09b5991f1e',
    messagingSenderId: '910614264123',
    projectId: 'ddwa-c76bf',
    storageBucket: 'ddwa-c76bf.appspot.com',
    iosBundleId: 'com.example.dwa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAJmv7VMrnGOUKUegBDzP9z_yEU9HU-lk',
    appId: '1:910614264123:ios:0d56276a83853480991f1e',
    messagingSenderId: '910614264123',
    projectId: 'ddwa-c76bf',
    storageBucket: 'ddwa-c76bf.appspot.com',
    iosBundleId: 'com.example.dwa.RunnerTests',
  );
}
